name: "Node: Build Application Refactored"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - "release/*"

jobs:
  dummy-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step 1
        run: echo "This is dummy job 1"

  deploy-production-release:
    needs: [dummy-job-1]
    if: ${{ needs.dummy-job-1.result == 'success' || needs.dummy-job-1.result == 'skipped' }}
    uses: ./.github/workflows/zxf-deploy-production-release-reusable.yaml
